stages:
  - build

stg-build:
  stage: build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - build
  only:
    - staging
  script:
    - npm install
    - npm run build -- --extra-webpack-config webpack.extra.js
    - rm -rf /var/www/stg-root/*
    - cp -r dist/ceit94/* /var/www/stg-root/

prod-build:
  stage: build
  variables:
    GIT_STRATEGY: fetch
  tags:
    - build
  only:
    - master
  script:
    - npm install
    - npm run build -- --prod --extra-webpack-config webpack.extra.js
    - rm -rf /var/www/prod-root/*
    - cp -r dist/ceit94/* /var/www/prod-root/
